"""
Opening element class for BIM as Code.

Openings are voids in horizontal elements (floors, roofs) for
stairs, shafts, skylights, and other penetrations.
"""

from typing import List, Tuple, Optional, TYPE_CHECKING
from build123d import extrude, Polygon, Location, Compound
from bimascode.core.element import Element
from bimascode.utils.units import Length, normalize_length

if TYPE_CHECKING:
    from bimascode.architecture.floor import Floor
    from bimascode.architecture.roof import Roof


class Opening(Element):
    """
    An opening (void) in a floor or roof element.

    Openings are defined by a polygon boundary and create voids
    in their host element through boolean subtraction.
    """

    def __init__(
        self,
        host_element,
        boundary: List[Tuple[float, float]],
        depth: Optional[Length | float] = None,
        name: Optional[str] = None,
        description: Optional[str] = None
    ):
        """
        Create an opening.

        Args:
            host_element: Floor or Roof that hosts this opening
            boundary: List of (x, y) coordinates defining opening boundary
            depth: Opening depth (defaults to host element thickness + 2mm)
            name: Optional name for this opening
            description: Optional description
        """
        super().__init__(name=name or "Opening", description=description)

        self._host_element = host_element
        self._boundary = boundary
        # guid is already generated by Element.__init__

        # Calculate depth (use host thickness + 2mm for clean cut if not specified)
        if depth is None:
            depth = host_element.thickness + 2
        self._depth = normalize_length(depth).mm

    @property
    def host_element(self):
        """Get the host element (Floor or Roof)."""
        return self._host_element

    @property
    def boundary(self) -> List[Tuple[float, float]]:
        """Get the opening boundary polygon."""
        return self._boundary.copy()

    @property
    def depth(self) -> float:
        """Get opening depth in millimeters."""
        return self._depth

    @property
    def area(self) -> float:
        """
        Calculate opening area in square millimeters.

        Uses the Shoelace formula for polygon area.
        """
        boundary = self._boundary
        if len(boundary) < 3:
            return 0.0

        # Shoelace formula
        area = 0.0
        n = len(boundary)
        for i in range(n):
            j = (i + 1) % n
            area += boundary[i][0] * boundary[j][1]
            area -= boundary[j][0] * boundary[i][1]

        return abs(area) / 2.0

    @property
    def area_m2(self) -> float:
        """Get opening area in square meters."""
        return self.area / 1_000_000.0

    def get_centroid(self) -> Tuple[float, float]:
        """
        Calculate the centroid of the opening boundary.

        Returns:
            (x, y) coordinates of centroid
        """
        boundary = self._boundary
        if len(boundary) == 0:
            return (0.0, 0.0)

        x_sum = sum(p[0] for p in boundary)
        y_sum = sum(p[1] for p in boundary)
        n = len(boundary)

        return (x_sum / n, y_sum / n)

    def get_opening_geometry(self) -> Compound:
        """
        Get the void geometry for boolean subtraction.

        The opening is created as an extruded polygon positioned
        to cut through the host element.

        Returns:
            build123d Compound for boolean subtraction
        """
        # Create polygon from boundary
        poly = Polygon(*self._boundary)

        # Extrude to create solid
        opening_solid = extrude(poly, amount=self._depth)

        # Position below the host element surface for clean cut
        # The opening should extend slightly below z=0 to ensure complete cut
        opening_solid = opening_solid.locate(Location((0, 0, -1)))

        return Compound(children=[opening_solid])

    def set_boundary(self, boundary: List[Tuple[float, float]]) -> None:
        """
        Set the opening boundary.

        Args:
            boundary: List of (x, y) coordinates
        """
        self._boundary = boundary
        self._host_element.invalidate_geometry()

    def set_depth(self, depth: Length | float) -> None:
        """
        Set the opening depth.

        Args:
            depth: New depth value
        """
        self._depth = normalize_length(depth).mm
        self._host_element.invalidate_geometry()

    def to_ifc(self, ifc_file, ifc_building_storey, ifc_host_element):
        """
        Export opening to IFC as IfcOpeningElement.

        Args:
            ifc_file: IFC file object
            ifc_building_storey: IFC building storey
            ifc_host_element: IFC entity that hosts this opening

        Returns:
            IfcOpeningElement entity
        """
        from bimascode.export.ifc_geometry import build123d_to_ifc_brep

        building = self._host_element.level.building
        centroid = self.get_centroid()

        # Create placement for opening (relative to host element)
        opening_location = ifc_file.createIfcCartesianPoint(
            (float(centroid[0]), float(centroid[1]), 0.0)
        )

        opening_axis_placement = ifc_file.createIfcAxis2Placement3D(
            opening_location,
            ifc_file.createIfcDirection((0.0, 0.0, 1.0)),
            ifc_file.createIfcDirection((1.0, 0.0, 0.0))
        )

        opening_placement = ifc_file.createIfcLocalPlacement(
            ifc_host_element.ObjectPlacement,
            opening_axis_placement
        )

        # Create opening element
        ifc_opening = ifc_file.create_entity(
            "IfcOpeningElement",
            GlobalId=self.guid,
            OwnerHistory=building._ifc_owner_history,
            Name=self.name,
            Description=self.description or "Floor/Roof opening",
            ObjectPlacement=opening_placement,
            PredefinedType="OPENING"
        )

        # Create opening geometry
        opening_geom = self.get_opening_geometry()
        if opening_geom:
            ifc_brep = build123d_to_ifc_brep(opening_geom, ifc_file)
            if ifc_brep:
                shape_representation = ifc_file.createIfcShapeRepresentation(
                    ifc_file.by_type("IfcGeometricRepresentationContext")[0],
                    "Body",
                    "Brep",
                    [ifc_brep]
                )

                product_shape = ifc_file.createIfcProductDefinitionShape(
                    None, None, [shape_representation]
                )
                ifc_opening.Representation = product_shape

        # Link opening to host element (IfcRelVoidsElement)
        ifc_file.createIfcRelVoidsElement(
            self._generate_guid(),
            building._ifc_owner_history,
            f"{self.name}VoidsElement",
            None,
            ifc_host_element,
            ifc_opening
        )

        return ifc_opening

    def __repr__(self) -> str:
        return (
            f"Opening(name='{self.name}', area={self.area_m2:.2f}m², "
            f"depth={self._depth:.1f}mm)"
        )


# Helper function to create rectangular openings
def create_rectangular_opening(
    host_element,
    center: Tuple[float, float],
    width: Length | float,
    length: Length | float,
    depth: Optional[Length | float] = None,
    name: Optional[str] = None
) -> Opening:
    """
    Create a rectangular opening.

    Args:
        host_element: Floor or Roof to host the opening
        center: (x, y) center point of opening
        width: Opening width (X direction)
        length: Opening length (Y direction)
        depth: Opening depth (defaults to host thickness)
        name: Optional name

    Returns:
        Opening with rectangular boundary
    """
    w = normalize_length(width).mm / 2
    l = normalize_length(length).mm / 2
    cx, cy = center

    boundary = [
        (cx - w, cy - l),
        (cx + w, cy - l),
        (cx + w, cy + l),
        (cx - w, cy + l),
    ]

    return Opening(
        host_element=host_element,
        boundary=boundary,
        depth=depth,
        name=name or "Rectangular Opening"
    )


def create_circular_opening(
    host_element,
    center: Tuple[float, float],
    radius: Length | float,
    segments: int = 32,
    depth: Optional[Length | float] = None,
    name: Optional[str] = None
) -> Opening:
    """
    Create a circular opening (approximated as polygon).

    Args:
        host_element: Floor or Roof to host the opening
        center: (x, y) center point of opening
        radius: Opening radius
        segments: Number of polygon segments (default 32)
        depth: Opening depth (defaults to host thickness)
        name: Optional name

    Returns:
        Opening with circular boundary
    """
    import math

    r = normalize_length(radius).mm
    cx, cy = center

    boundary = []
    for i in range(segments):
        angle = 2 * math.pi * i / segments
        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        boundary.append((x, y))

    return Opening(
        host_element=host_element,
        boundary=boundary,
        depth=depth,
        name=name or "Circular Opening"
    )
